// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9KIRqbuFBSHaN72uwP0Dcp4RlYPWCjy4',
    appId: '1:230005785507:web:5cefeb1d320b0c32fe5016',
    messagingSenderId: '230005785507',
    projectId: 'detective-85a70',
    authDomain: 'detective-85a70.firebaseapp.com',
    storageBucket: 'detective-85a70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEjZ00e9wE2OYUi0rK877lrFHjJ2VS_w',
    appId: '1:230005785507:android:031c3712276e1840fe5016',
    messagingSenderId: '230005785507',
    projectId: 'detective-85a70',
    storageBucket: 'detective-85a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHuIhx7wSv4mZ0G6KZimrsl_7yo0q8E4',
    appId: '1:230005785507:ios:82f24e5e6ddb0542fe5016',
    messagingSenderId: '230005785507',
    projectId: 'detective-85a70',
    storageBucket: 'detective-85a70.firebasestorage.app',
    iosBundleId: 'com.example.detective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHuIhx7wSv4mZ0G6KZimrsl_7yo0q8E4',
    appId: '1:230005785507:ios:82f24e5e6ddb0542fe5016',
    messagingSenderId: '230005785507',
    projectId: 'detective-85a70',
    storageBucket: 'detective-85a70.firebasestorage.app',
    iosBundleId: 'com.example.detective',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9KIRqbuFBSHaN72uwP0Dcp4RlYPWCjy4',
    appId: '1:230005785507:web:9e154f0ba8b28a30fe5016',
    messagingSenderId: '230005785507',
    projectId: 'detective-85a70',
    authDomain: 'detective-85a70.firebaseapp.com',
    storageBucket: 'detective-85a70.firebasestorage.app',
  );
}
